# Generated by Django 3.0.2 on 2020-01-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('card ', 'Card')], default='cash', max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Trasaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Amount')),
            ],
        ),
    ]
