# Generated by Django 3.0.2 on 2020-01-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('goal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Amount')),
            ],
        ),
    ]
