# Generated by Django 3.0.2 on 2020-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='colected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
