# Generated by Django 3.0.2 on 2020-02-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20200201_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Profile'),
        ),
    ]
