# Generated by Django 3.0.2 on 2020-02-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20200204_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasaction',
            name='transaction_amount',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
