# Generated by Django 3.0.2 on 2020-02-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20200204_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Profile'),
        ),
    ]
